# Generated by Django 5.2.5 on 2025-08-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_excerpt_article_image_article_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={},
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='Correct answer for scoring'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1, help_text='Points for correct answer'),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Is this the correct answer?'),
        ),
        migrations.AddField(
            model_name='response',
            name='max_possible_score',
            field=models.PositiveIntegerField(default=0, help_text='Maximum possible score'),
        ),
        migrations.AddField(
            model_name='response',
            name='score',
            field=models.PositiveIntegerField(default=0, help_text='Total points earned'),
        ),
        migrations.AddField(
            model_name='response',
            name='slot_number',
            field=models.PositiveIntegerField(default=1, help_text='Which slot number this response used'),
        ),
        migrations.AddField(
            model_name='survey',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='max_slots',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of VIP users who can answer'),
        ),
        migrations.AddField(
            model_name='survey',
            name='slot_duration_hours',
            field=models.PositiveIntegerField(default=24, help_text='How long each slot is valid (in hours)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
